### ISSUE TITLE
Remove submit button

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/gwas-deposition-ui#281]
This is most likely already there - adding the ticket just to have it part of the EPIC.

**Comment by twhetzel** [comment]
@tudorgroza where is the spec for this Epic to see what the final decision is for this workflow change?

Are there any cases where displaying the Submit button is needed at all with the new workflow?

**Comment by twhetzel** [comment]
@tudorgroza previously if there was an error with the web service call to submit the submission using the PUT call in the form of`BASE_URI + '/submissions/' + submissionId + '/submit'`, the UI would display an error message.
What error response will be returned now from this call? 
How will users be notified of an issue to submit a submission?

**Comment by twhetzel** [comment]
Talked with Tudor and any possible error in the automatic submit process is not a concern of the UI and can be ignored.

**Comment by eks-ebi** [comment]
Tested 2020-06-24

Confirm, the Submit button has been removed from the Submission details page.

Example: http://193.62.54.159/gwas/deposition/submission/5ef374a73b86f30001dafff4
