### ISSUE TITLE
Rename "Upload submission" button to "Submit submission form"

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-deposition-ui#284]
Based on the comment in the spec [1] to no longer require the submitter to press "Submit" for a valid submission the following text/button label changes are needed: 
 - [x] the button named "Upload submission" needs to be re-named to "Submit submission form"
 - [x] update the steps listed in the Submission steps overview section

These updates are in branch: `epic90_pass_valid_files`

[1] https://docs.google.com/document/d/1pVI228G--Bb2EFhCqXt678Qj-T8NBjODCaOpzf9n3_M/edit

**Comment by eks-ebi** [comment]
Tested 2020-06-24

Confirm, the button has been renamed to "Submit submission form" and the Submission Step Overview is consistent with the new workflow.

Example: http://193.62.54.159/gwas/deposition/submission/5eb1bafbcbce5e0001b7a3c4
