### ISSUE TITLE
Do not display button to download GCSTs when a submission is VALID

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-deposition-ui#285]
The rule for when GCSTs are available has changed so the button to download GCSTs should only be available when a submission has status SUBMITTED but no longer when the status is VALID

Check if there are any further submission status label changes from the Depo sync/Ingest process after status SUBMITTED

This work is in branch: `epic90_pass_valid_files`

**Comment by twhetzel** [comment]
UAT
1. Submitter logs into the Deposition App
2. Submitter follows submission workflow to create a BoW or select PMID
3. Submitter completes their submission

On successful validation and seeing the status label "Submitted" for the "Submission Report" field "Current status", the button to download GCSTs should be displayed and GCSTs should be able to be downloaded.

The button to download GCSTs should not be displayed for any other submission status.

**Comment by eks-ebi** [comment]
Tested 2020-06-24

Confirm, the Download GCSTs button is no longer displayed for submissions that have the status VALID

Example: http://193.62.54.159/gwas/deposition/submission/5eb1bafbcbce5e0001b7a3c4
