### ISSUE TITLE
Show different message for VALID and SUBMITTED status to submitting authors 

### ISSUE THREAD

**Issue by buniello** [EBISPOT/gwas-deposition-ui#287]
MESSAGE TO SHOW AFTER VALIDATION - “If you are happy with the validated data please “Submit”

SUBMITTED DATA - “Thank you for submitting your data. Please contact gwas-subs@ebi.ac.uk if changes are needed”

NOTE: Since this ticket was added, the submit button is now requested to be removed.

**Comment by twhetzel** [comment]
The MESSAGE TO SHOW AFTER VALIDATION  is no longer needed since a successful submission will pass automatically to the submitted status without the user needing to press submit.
