### ISSUE TITLE
Add step to wait for Globus notification before uploading submission form

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-deposition-ui#288]
For larger summary stats files or submissions with lots of summary stats files, the time to transfer these to Globus can be timely. If a user uploads their submission form before receiving the "Globus notification" email, the submission will fail even if everything else is correct because the md5 values will not match between the submission form and the content of the file on Globus. 

 - [x] add a new step above "Submit submission form" to indicate the user should wait to receive the Globus notification emails before proceeding

Suggested text:
4 - Wait to receive an email confirmation from "Globus" that all summary statistics files have successfully been transferred

**Comment by ljwh2** [comment]
This text looks fine to me

**Comment by eks-ebi** [comment]
Tested 2020-06-24

Confirm, the new text has been added to the Submission Steps Overview. I think these instructions should be clear to users.

Example: http://193.62.54.159/gwas/deposition/submission/5eb1bafbcbce5e0001b7a3c4
