### ISSUE TITLE
Display Last Updated date in Submissions table

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-deposition-ui#290]
On the submissions page, for the tab Active Submissions, add the column last updated to the table so that curators know when updates have occurred.

**Comment by twhetzel** [comment]
Ready for QA

**Comment by eks-ebi** [comment]
Tested 2020-07-27 on sandbox - looks good!

**Comment by twhetzel** [comment]
Thanks, I'll push this to production
