### ISSUE TITLE
more informative description for Globus account entry

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-deposition-ui#292]
We need to add a more informative help to guide the users to input the correct the "globus email" field on the submission details page here:

![image.png](https://images.zenhubusercontent.com/5e57db4a23eb16cef275ef41/0667fbd6-f638-4aa7-8512-503faeafa791)

**Comment by jdhayhurst** [comment]
What we need is the user's **Primary identity**. This can be found here: https://app.globus.org/account/identities.
- I propose changing the text next to the checkbox to "Enter your Globus account primary identity (required to submit summary statistics)"
- Instead of "Globus email*", perhaps "Globus identity (usually an email address)"?
- instead of "Add valid email to link to Globus" --> "Add valid Globus identity"

We could add a link to https://app.globus.org/account/identities from "Globus account primary identity".

**Comment by ljwh2** [comment]
I agree with James' proposal. @sprintell will work on this after Trish handover

**Comment by ljwh2** [comment]
Discussed in iteration meeting 31/3/21, the link should be added as proposed above https://app.globus.org/account/identities

**Comment by jdhayhurst** [comment]
Tested on Sandbox - looks good - thanks @ala-ebi
