### ISSUE TITLE
Unable to search publications by author

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/gwas-deposition-ui#74]
Search by author is not possible - I tried to “find” but that only works on the entries on the page you are looking at - JoM
There was no requirement to search by author. The help text in the Search says what the input for search is - TW

Note: low priority, non-blocker.

**Comment by twhetzel** [comment]
TG has implemented a Search by Author, it is currently case sensitive and can be accessed as: http://193.62.54.159/backend/v1/publications?author=Wang

**Comment by twhetzel** [comment]
Bug when typing in author name since search happens for each letter added. Sometimes search result is returned and then disappears.

**Comment by twhetzel** [comment]
Increased the `debounceInterval` from the default of `200ms` to `2500ms` to allow for a pause in user typing before initiating the API call. This appears to have helped to resolve the issue above. 

However, _if_ a user starts typing more letters after the search starts, e.g. spinner is visible, then the above behaviour occurs. NOTE: the current search behaviour with MongoDB does not support partial search and based on some reading the order of the api results are not guarenteed to be in the same order as they are sent.


TODO: Disable search field when spinner is visible to prevent additional searches once an search api call has been initiated.

**Comment by twhetzel** [comment]
Merged into master, but have not disabled search field when spinner is visible.
