### ISSUE TITLE
Test authenticated submission view

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/gwas-deposition-ui#75]
To test:
Test when authentication enabled - Even when logged into own account, all users’ submissions are visible - is this just temporary? John explained that curators will be able to see all submissions, but external submitters will only see their own submissions - ES
I think this means that we are seeing the correct functionality for curators, but we will need to test with outside users to make sure they cannot see other people’s submissions - ES
Authentication is not enabled so currently there is no difference in the data visibility for any user. 

Once authentication is enabled, last I heard the plan is that all curators will be able to see all submissions and external users will only be able to see their own submissions - TW

**Comment by twhetzel** [comment]
Authentication on the GET Submissions endpoint is currently enabled and with the set of curators currently based on emails (and my email in this list), I am able to see all submissions.
