### ISSUE TITLE
Clarify "Upload File" for SS

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/gwas-deposition-ui#77]
Could we have more explanation under ‘upload file’ for SS that you don’t want the SS file to be uploaded, but the metadata Excel file with a link in? EL

Currently supported locations are Google Drive, Dropbox, and public FTP.

**Comment by twhetzel** [comment]
For now, the curator suggests to change the button text to "Upload SS Template" for SS submissions to be parallel with the text for the button to download the template of "Download SS Template". After the UX meeting, there may be additional requests for a help icon with links to the new docs for the Depo app.

**Comment by twhetzel** [comment]
Closed with https://github.com/EBISPOT/gwas-deposition-ui/pull/83
